products = [
    {
        "id": 1,
        "name": "Laptop",
        "category": "electronics",
        "price": 1200,
        "rating": 4.7,
        "description": "A powerful laptop for work and study.",
    },
    {
        "id": 2,
        "name": "Phone",
        "category": "electronics",
        "price": 800,
        "rating": 4.5,
        "description": "A modern smartphone.",
    },
    {
        "id": 3,
        "name": "Keyboard",
        "category": "accessories",
        "price": 100,
        "rating": 4.2,
        "description": "Mechanical keyboard.",
    },
    {
        "id": 4,
        "name": "Mouse",
        "category": "accessories",
        "price": 50,
        "rating": 4.0,
        "description": "Wireless computer mouse.",
    },
    {
        "id": 5,
        "name": "Monitor",
        "category": "electronics",
        "price": 350,
        "rating": 4.6,
        "description": "27-inch computer monitor.",
    },
    {
        "id": 6,
        "name": "Desk",
        "category": "furniture",
        "price": 300,
        "rating": 4.3,
        "description": "Office desk for home or work.",
    },
    {
        "id": 7,
        "name": "Chair",
        "category": "furniture",
        "price": 250,
        "rating": 4.4,
        "description": "Comfortable office chair.",
    },
]